apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: irgashevsardor/tasks-app
        ports:
        - containerPort: 3000
        env:
          - name: MYSQL_USER
            value: "user"
          - name: MYSQL_HOST
            value: "mysql-service"
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-env-data
                key: MYSQL_PASSWORD
          - name: MYSQL_DB
            value: "list"
