apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
spec:
  rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: app-service
            servicePort: 3000
